### ISSUE TITLE
farfetch 

### ISSUE THREAD

**Issue by sppmaster** [Shadow096/PokeSniperHelper#2]
Looks to me that when it find farfetch and type it into PokeSniper, PokeSniper crash. Maybe is fixable by removing the ' ?

**Comment by Shadow096** [comment]
Done

**Comment by sppmaster** [comment]
How I can update it? Just insert the old. exe in the same folder of the new files?

**Comment by Shadow096** [comment]
Download new version from here:
https://github.com/Shadow096/PokeSniperHelper/releases

**Comment by sppmaster** [comment]
Awesome, do you accept donation? 

PS: To download all pokemons I need to select N in the first screen right? The typer will use multiple sources automatically?

**Comment by Shadow096** [comment]
Yes, type N
